### ISSUE TITLE
Missing metadata

### ISSUE THREAD

**Issue by christianbundy** [Gargron/blurhash.js#1]
Hi! I know this is a mirror, but I'm unclear on where the upstream repository is. The npm package doesn't reference any repository or metadata other than the authors so I'm not sure where else to post the issue, but it would be great if the npm package referenced the repo or bug tracker or *something*.

Super excited to try blurhash.js but hesitant to use a module without an upstream. :upside_down_face:

**Comment by Gargron** [comment]
I created this mirror before 1.0.0 was available on NPM, so technically this repository is not needed anymore. The real upstream is a currently private BitBucket repository, and it's not up to me to publish it. I can't really answer any issues or pull requests on here because the code isn't mine and the package is not published from my NPM account. I was told the upstream would be opened to the public "soon"
